### ISSUE TITLE
How to exclude what Alexa can do

### ISSUE THREAD

**Issue by 2devnull** [mike-grant/haaska#28]
I would like Alexa to only CLOSE the garage door and not have the ability to open it (unless it can pop up a confirm on my phone/smart watch - but that is for another day). How do I exclude that opening ability?

**Comment by Isstum** [comment]
Create a switch from switch template and publish this instead of the garage 
door?


Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 12. März 2018 4:12:04 nachm. schrieb 2devnull <notifications@github.com>:

**Comment by 2devnull** [comment]
Thank you, I will try it

**Comment by 2devnull** [comment]
Well, looking at the docs and asking alexa, it seems you can only say "turn on" or "turn off" the X garage door. Anyone know how to tell alexa to "open" or "close" it. I'm afraid mixing up turn on/turn off is will become an issue as it is not easily correlated with open/close in general.

**Comment by anthonylavado** [comment]
@2devnull Looking at the Alexa reference in general, they don't support any type of "Cover" or "Garage door" object through the Smart Home Skill API. As such, we wouldn't be able to change it or affect it. Even if we could, it would be a change in the core of Home Assistant - Haaska is simply just a relay for the commands that HA provides.

What I think you might be able to do, is create a "Routine" in the Alexa app. Name one "Close Garage Door", and have it set to send a "turn off" to the Garage Door item. Then, it should just activate by saying "Alexa, close Garage Door".

**Comment by 2devnull** [comment]
@anthonylavado - Thanks...I'll give that a try. 

It is strange that it doesn't officially support it, but covers items like my opengarage door system is seen by alexa, and if I say, "Alexa, turn off left garage door", it activates it.

**Comment by anthonylavado** [comment]
@2devnull With regards to the covers not being supported - I should have been a little clearer. The Alexa Smart Home interface doesn't understand what a "cover" or "door" is. So there's no special words or commands to handle it.

When designing the Alexa integration, the Home Assistant developers took a two-step approach: If the the object exists in Alexa (like a switch, or a door lock), then map it as the correct object. If the item doesn't exist in Alexa, it just presents it as a simple light switch instead. Because Home Assistant understands what a cover is, but Alexa doesn't, it just appears as a light switch.

That said, I can see why Alexa doesn't have any direct garage door stuff yet. Using the keyword "open" is trouble in the Alexa world, because that is reserved for launching new skills (e.g. "Alexa, open Weather Channel").

I think the best way to go to prevent opening at all, might be finding a way to map the garage door "cover" as a door lock. In the Alexa skill world, doors can be locked, but they can't be unlocked. That command is rejected by default. With my Lockitron, I can say "Alexa, lock the Front Door", and it works. If I say "Alexa. unlock the Front Door", it just replies saying it can't do that. I haven't looked at it in a while, but I wonder if you can "re-map" how the device looks to Alexa.

**Comment by trisk** [comment]
@2devnull The best solution is probably to create a [template cover](https://home-assistant.io/components/cover.template/) or [switch](https://home-assistant.io/components/switch.template/) entity with an empty handler for `open_cover` or `turn_on`, forward `close_cover` or `turn_off` to your real cover entity, and exclude the real entity from the alexa component.
