### ISSUE TITLE
No control options for Media Player

### ISSUE THREAD

**Issue by chaleta** [mike-grant/haaska#30]
Hello,

Many thanks for your Work. I've set up haaska as per the Wiki. All my devices have been discovered but I have no control over Media Player devices. I've listed them in display_categories: TV in Alexa HA Config section but they appear in Alexa without type and no control.

Looking at the bellow link about Smart Home Skills for Entertainment Devices there is support for 

Turn things on and off, Change the channel on a device, Change the input of a playback device, Control the playback of device; fast forward, rewind and pause Change the volume in incremental steps, Change the volume to anywhere on a continuous range.

https://developer.amazon.com/docs/smarthome/build-smart-home-skills-for-entertainment-devices.html

Many thanks for your help

**Comment by anthonylavado** [comment]
@chaleta Hey there. Haaska is just the “glue” that connects what Home Assistant can already do, to Alexa.

Because of the way it is built, we rely on Home Assistant to provide the correct categories and controls. We don’t actually create any devices, Haaska is just what connects Home Assistant to the Alexa service.

I would recommend making the request in the Home Assistant project, so they can work on it as needed. The last time I checked, they were working on Media Devices, but had some changes to be made still.
