### ISSUE TITLE
Haaska Support for Cover Component

### ISSUE THREAD

**Issue by mskressin** [mike-grant/haaska#32]
It is unclear from the documentation if Haaska supports cover components. I have the following cover component defined in my HA config file:

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Shades"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.bank_of_shades
        close_cover:
          service: switch.turn_off
          data:
            entity_id: switch.bank_of_shades
        stop_cover:
          service: switch.turn_off
          data:
            entity_id: switch.stop_all_shades

HA thinks this is a cover and allows me to operate it like a cover. Also, the device that shows up in the Alexa app has a type of "Door". However, when I say "Alexa open shades", Alexa says "Shades doesn't support that". However, if I say "Alexa turn on shades" that works. It is like haaska is somehow converting the cover component to a switch component.

**Comment by anthonylavado** [comment]
@mskressin Sorry about that, I'll make a note to be clearer in the documentation. Haaska does not do any of the device/category support itself, it is merely a relay for Home Assistant at this point. Basically, it's the same as HA Cloud.

It's Home Assistant's core code that decides how to present devices to Alexa. Right now, there's no Alexa Smart Home equivalent for a cover, so it usually falls back to being a Switch, but as you said, you've got it appearing as a door right now.

There are a few issues with this:
- Smart Locks can't be opened by voice with Alexa, so I imagine this is also an issue with door components
- "Open" is a reserved word in the Alexa world, because this is used for launching a skill, so it can never be used for commands
