### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#74]
*Opening a new issue for @zackcaussy.*

Hello Mike,
I don't know if it is correct to contact on this page or not but I have issue with haaska, maybe you can help me?

I ran under 2 different problem, I use the haaska guide from the wanderer, and I managed to install all, but Alexa wouldn't work for some reason.... I am kind of newbie, and I don't know what to do as it can be challenging to learn a new language when you don't know anything about it.

Well here is my issue:

I tried the set location for Ireland for my program in lambda. I got one error.
I tried location set to North Virginia for my program in lambda too, and I got another error.

I am based in France, so I should use Ireland I know but... it seems to be the same as louisefindlay23, which I guess you solved eventually.
So I post the first error maybe you will understand.

error:
{
"errorMessage": "Expecting property name enclosed in double quotes: line 39 column 1 (char 865)",
"errorType": "JSONDecodeError",
"stackTrace": [
[
"/var/task/haaska.py",
655,
"event_handler",
"config = Configuration('config.json')"
],
[

2nd error on Ireland Amazon:
{
"errorMessage": "'header'",
"errorType": "KeyError",
"stackTrace": [
[
"/var/task/haaska.py",
660,
"event_handler",
"name = event['header']['name']"
]
]
}

For info I use Hassbian, but followed all steps from the wanderer's page. All went well, except the execution. The result, is I cannot even discover any device from Alexa.

I don't know if you can help of not, but if you can big thank you))
Have a nice day

**Comment by anthonylavado** [comment]
@zackcaussy - Are you able to post what your Config.json tile looks like? Make sure to take out the real URL and Token.

Can you also check that the handler is set correctly in Lambda? See this screenshot: [Imgur](http://i.imgur.com/ZwA6HI2.jpg)

**Comment by zackcaussy** [comment]
@anthonylavado - Thank you for your support, so here is my Config.json:

{
  "url": "https://xxxxxxxxxxxxxxxx.duckdns.org:443",
  "bearer_token": "from home assistant long life token",
  "debug": true,
  "ssl_verify": true,
  "ssl_client": []
}

Yes, handler set correctly.

Maybe you will see something I am missing. Thank you

**Comment by anthonylavado** [comment]
@zackcaussy - I think we've got it there. It should look like this:
```json
{
"url": "https://xxxxxxxxxxxxxxxx.duckdns.org:443/api",
"bearer_token": "from home assistant long life token",
"debug": true,
"ssl_verify": true,
"ssl_client": []
}
```

**Comment by anthonylavado** [comment]
@zackcaussy - Wait - figured out the real reason. You still need to have the `/api`, but you are using the _old_ Haaska. You need to use the *new* one from here. This link will get you the new version: 
https://github.com/mike-grant/haaska/archive/master.zip

**Comment by zackcaussy** [comment]
@anthonylavado - I rarely say that but "OMG" you are a superstar!
You fixed the issue, I can't believe even me not knowing much about how to program made it!
You guys are excellent, and I am happy that you solved my issue, if you have new input, I will be happy to help you guys in the future, just remember I'm running Hassbian (I know I switch from Hassio...), but it's fantastic! Yeah, regarding the issue, it was on the old link, so I guess, things need to be little tweeked. As well as that, I re-compiled the file all together, so I renamed the hasska master into haaska, I thought it would be easier instead of restarting everything from scratch on lambda.
Well, I can only say big thank you to you, now I have little things to change such as names on my switches, some are sharing the same title, so I guess they all need to have different way to be called, as Alexa French is having trouble to recognise the names correctly. But it works, and this is great! Have a great weekend, and keep this good work going, you are amazing!
