### ISSUE TITLE
Server is unresponsive when changing light color

### ISSUE THREAD

**Issue by IDmedia** [mike-grant/haaska#76]
I have everything configured and working. However, when I change the color of my light, though the Alexa app or using my voice, I get the error message "Server is unresponsive". The action is still performed, but Alexa respons with "I don't know what went wrong".

I'm using the IKEA smart lights and have set the lambda function timeout to 30 seconds. Any other ideas what I might have missed?

**Comment by anthonylavado** [comment]
@IDmedia I agree with @mikeage here.

Whenever you have a server error with haaska, it’s either a problem where it can’t reach your Home Assistant install, or it’s not getting back the information it expects from HA.

If it was the first one, then no functions at all would be working. If other commands work, but some fail, then it’s usually the second one. Since haaska just acts as the glue that connects Alexa to your install, we depend on fixes in the Home Assistant code to make things work.

**Comment by IDmedia** [comment]
Awesome, thanks for the information!
