### ISSUE TITLE
How does SSL_Client work?

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#77]
In the config sample, we have this line:
https://github.com/mike-grant/haaska/blob/f5f4004084eddeb17cc2cd831a774984aebc49be/config/config.json.sample#L6

Unfortunately, I'm not really sure how it should be used. We've defaulted to `SSL_VERIFY` true, which is working well for a lot of users, but I'm not sure what to recommend here.

**Comment by anthonylavado** [comment]
@mike-grant Are you able to shed any light on how this works?

**Comment by mike-grant** [comment]
It's not exactly the "best" name for the parameter. But it allows someone to pass in a custom certificate e.g. if they have a self signed certificate.

**Comment by anthonylavado** [comment]
@mike-grant Got it. I haven't been able to test it reliably with my Let's Encrypt cert yet, but it seems like a feature we can leave alone for now. I understand now that it means "SSL Client Certificate".

We can change it later :)

**Comment by anthonylavado** [comment]
@mike-grant Are you able to shed some light on what cert formats this supports?

**Comment by anthonylavado** [comment]
Looks like I’ll need to figure this out to help #94.

**Comment by mike-grant** [comment]
I believe it needs to be .pem . I can't really see the need for many people to use this when LetsEncrypt is about.

**Comment by doppiaemme** [comment]
Hi, 
my setup works disabling ssl_verify but when I enable it I get the SSL error.
I have tried leaving `ssl_client` empty

`"errorMessage": "HTTPSConnectionPool(host='xxxx.xxxx.dev', port=443): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))",`

then I tried to copy my .pem file into the homeassistant config folder and changed 
"ssl_client": "mycert.pem" and now I get 
```
"errorMessage": "Could not find the TLS certificate file, invalid path: mazzeo.pem",
  "errorType": "OSError",
```

Please note I don't use Let'sEncrypt but I purchased an SSL wildcard cert.
any idea?
thanks!
