### ISSUE TITLE
SSL Error - Certificate verify failed

### ISSUE THREAD

**Issue by anthonylavado** [mike-grant/haaska#94]
Unfortunately it doesn't work...

{
  "url": "https://XXXXXX.org:8123/api",
  "debug": true,
  "ssl_verify": true,
  "ssl_client": [],
  "bearer_token": "XXXXXXXXXXXXXX"
}

result:

Response:
{
  "errorMessage": "HTTPSConnectionPool(host='XXXXXXXX.org', port=8123): Max retries exceeded with url: /api/alexa/smart_home (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))",
  "errorType": "SSLError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      109,
      "event_handler",
.........

_Originally posted by @tarat73 in https://github.com/mike-grant/haaska/issues/92#issuecomment-460161849_

**Comment by anthonylavado** [comment]
Hi @tarat73 - Can you please let me know how you created your SSL Certificate?

**Comment by tarat73** [comment]
> Hi @tarat73 - Can you please let me know how you created your SSL Certificate?
Hallo anthonylavado,

sudo openssl req -new -x509 -days 800 -keyout key/vhost1.key -out crt/vhost1.crt -nodes -subj  '/O=Family Company/OU=Virtual Host Website department/CN=XXX.XXXXX.org'

**Comment by anthonylavado** [comment]
Oh okay, so it’s a self signed cert? If so, then that’s why the validation with SSL fails.

It only knows certificates from trusted authorities (like when you get one from Let’s Encrypt for example). There should be a way to have it understand and trust this (thats the SSL_Client option in the config), but unfortunately I don’t understand it (I’m mainly the docs/support guy here).

Sorry about that!

**Comment by psfell** [comment]
If anyone is hitting the issue with verification failing (Ive seen this on a number of Forums, but not the solution.) .. just posting here since #92 got closed...
Having spent hours trying to fix this, I eventually got verification to work using a Lets Encrypt cert, but had to create a cert bundle rather than just the single cert that Lets Encrypt gave me. 
By default the certificate.crt you get from LetsEncrypt contains only the one that they create and sign for you. Some systems insist that the https server (HA in this case) has the full chain of certs in the one file.
To do this, you just need to use an editor and copy/paste all of:
1. Your certificate (that Lets Encrpyt gave you - called certificate.crt)
2. The Lets Encrypt intermediate CA certificate (this is the one provided by Lets Encrypt and called ca_bundle.crt)
3. The root certificate that signed Lets Encrypts CA Cert (You can download it from here: https://letsencrypt.org/certificates/ but make sure you pick the right one)

The order is important, and actually I found it had to be in the order 1. Your Cert, 2. The Root Cert, 3. lets Encrypt CA Cert.
It should look something like this:

-----BEGIN CERTIFICATE-----
MIIFlzCCBH+g......................
.........eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgA......................
.........eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK......................
.........eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----

Note that it also needs to be readable by homeassistant, so be careful of dos-to-unix conversion issues if you are editing under windows.. Also make sure each of the ---BEGIN--- and ---END--- statements are each on a separate line (as above).

Once you've created this file, copy it up to homeassistant (probably the ssl directory) and update your configuration.yaml to use this new file rather than the previous certificate.crt (or simply replace the existing certificate.crt with this combined one)

Just a side note, the other issue I found was that running haaska in AWS (Ireland/Europe instance), HA had to be accessible via port 443 rather than HA's standard 8123. Once I updated that, all worked perfectly!
